### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

### ISSUE THREAD

**Issue by thistleknot** [summarizepaper/summarizepaper#6]
Python 3.10.9
Oracle Linux 8.3

installed via a new venv and ran

```pip install -r requirements.txt
python3 manage.py runserver
```
```
(summarizer) (base) [root@pve0 summarizepaper]# python manage.py
WARNING:root:No DATABASE_URL environment variable set, and so no databases setup

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser

[channels]
    runworker

[contenttypes]
    remove_stale_contenttypes

[daphne]
    runserver

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    optimizemigration
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

[sessions]
    clearsessions

[sitemaps]
    ping_google

[staticfiles]
    collectstatic
    findstatic
(summarizer) (base) [root@pve0 summarizepaper]# python manage.py rrunserver
WARNING:root:No DATABASE_URL environment variable set, and so no databases setup
Unknown command: 'rrunserver'. Did you mean runserver?
Type 'manage.py help' for usage.
(summarizer) (base) [root@pve0 summarizepaper]# python manage.py runserver
WARNING:root:No DATABASE_URL environment variable set, and so no databases setup
WARNING:root:No DATABASE_URL environment variable set, and so no databases setup
Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 14, 2024 - 21:11:14
Django version 4.1.6, using settings 'arxivsummarizer.settings'
Starting ASGI/Daphne version 4.1.2 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
joe
ERROR:daphne.server:Exception inside application: The SECRET_KEY setting must not be empty.
Traceback (most recent call last):
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/utils/deprecation.py", line 148, in __acall__
    response = await sync_to_async(
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/root/miniconda3/envs/textgen/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/django/contrib/messages/middleware.py", line 12, in process_request
    request._messages = default_storage(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/contrib/messages/storage/__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/contrib/messages/storage/fallback.py", line 16, in __init__
    self.storages = [
  File "/data/summarizer/lib/python3.10/site-packages/django/contrib/messages/storage/fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
  File "/data/summarizer/lib/python3.10/site-packages/django/contrib/messages/storage/cookie.py", line 77, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/signing.py", line 112, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
  File "/data/summarizer/lib/python3.10/site-packages/django/conf/__init__.py", line 101, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/utils/deprecation.py", line 152, in __acall__
    response = response or await self.get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = await sync_to_async(
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/root/miniconda3/envs/textgen/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/root/miniconda3/envs/textgen/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 488, in thread_handler
    return func(*args, **kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 366, in get_traceback_data
    "settings": self.filter.get_safe_settings(),
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 150, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "/data/summarizer/lib/python3.10/site-packages/django/conf/__init__.py", line 101, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/utils/deprecation.py", line 152, in __acall__
    response = response or await self.get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = await sync_to_async(
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/root/miniconda3/envs/textgen/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/root/miniconda3/envs/textgen/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 488, in thread_handler
    return func(*args, **kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 366, in get_traceback_data
    "settings": self.filter.get_safe_settings(),
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 150, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "/data/summarizer/lib/python3.10/site-packages/django/conf/__init__.py", line 101, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/utils/deprecation.py", line 152, in __acall__
    response = response or await self.get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = await sync_to_async(
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/root/miniconda3/envs/textgen/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/root/miniconda3/envs/textgen/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 488, in thread_handler
    return func(*args, **kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 366, in get_traceback_data
    "settings": self.filter.get_safe_settings(),
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 150, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "/data/summarizer/lib/python3.10/site-packages/django/conf/__init__.py", line 101, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/utils/deprecation.py", line 152, in __acall__
    response = response or await self.get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = await sync_to_async(
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/root/miniconda3/envs/textgen/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/root/miniconda3/envs/textgen/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 488, in thread_handler
    return func(*args, **kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 366, in get_traceback_data
    "settings": self.filter.get_safe_settings(),
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 150, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "/data/summarizer/lib/python3.10/site-packages/django/conf/__init__.py", line 101, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/whitenoise/middleware.py", line 124, in __call__
    return self.get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
  File "/root/miniconda3/envs/textgen/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/root/miniconda3/envs/textgen/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = await sync_to_async(
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/root/miniconda3/envs/textgen/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/root/miniconda3/envs/textgen/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 488, in thread_handler
    return func(*args, **kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 366, in get_traceback_data
    "settings": self.filter.get_safe_settings(),
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 150, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "/data/summarizer/lib/python3.10/site-packages/django/conf/__init__.py", line 101, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 366, in get_traceback_data
    "settings": self.filter.get_safe_settings(),
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 150, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "/data/summarizer/lib/python3.10/site-packages/django/conf/__init__.py", line 101, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/whitenoise/middleware.py", line 124, in __call__
    return self.get_response(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 366, in get_traceback_data
    "settings": self.filter.get_safe_settings(),
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 150, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "/data/summarizer/lib/python3.10/site-packages/django/conf/__init__.py", line 101, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/summarizer/lib/python3.10/site-packages/django/contrib/staticfiles/handlers.py", line 101, in __call__
    return await self.application(scope, receive, send)
  File "/data/summarizer/lib/python3.10/site-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/asgi.py", line 155, in __call__
    await self.handle(scope, receive, send)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/asgi.py", line 178, in handle
    response = await self.get_response_async(request)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/base.py", line 162, in get_response_async
    response = await self._middleware_chain(request)
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/root/miniconda3/envs/textgen/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/root/miniconda3/envs/textgen/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/data/summarizer/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 366, in get_traceback_data
    "settings": self.filter.get_safe_settings(),
  File "/data/summarizer/lib/python3.10/site-packages/django/views/debug.py", line 150, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "/data/summarizer/lib/python3.10/site-packages/django/conf/__init__.py", line 101, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

```

**Comment by qkral** [comment]
You need to learn how to use django and put in a secret_key

**Comment by thistleknot** [comment]
Expecting others to know how to fully implement the tech stack is kind of short sighted but okay. Thanks for the cookie crumb

**Comment by qkral** [comment]
It is indeed expected that if you want to implement a code in django you at least know how to run a first django basic example yourself. Add the secret key as I said before, there is nothing else I could provide except for a django tutorial.

**Comment by thistleknot** [comment]
Was expecting turnkey. I don't have experience setting up Django. Which is why I asked. Others will have similar issues. Once I figure it out I'll update the post with the necessary instructions. I see there is a random_secret_key function that could be used
